source("/home/rstudio/morph/scripts/db_functions.R")
PgMakeDb("brant")
PgInit("brant")
PgPlr("brant")
PgLoadRaster(x=330,y=330)
PgMakeGrat(xdim=33,ydim=33)
PgPSuitable(depth=-0.2,height=0.2)
PgAddResource()
PgLoadVector()
PgAddVector()
source("/home/rstudio/morph/scripts/Xtide.R")
source("/home/rstudio/morph/scripts/climate.R")
PgBackupDb()

